unit mainform;

{$mode objfpc}{$H+}

interface

uses
  LazUTF8,Classes, SysUtils, FileUtil, Forms, Controls, Graphics, Dialogs, ExtCtrls,
  ComCtrls, StdCtrls, ActnList, Menus,

  uoptions,uscaner,uscanresult,uwriter;

  type

  { TForm1 }

  TForm1 = class(TForm)
    GDBobjinsp1: TPanel;
    MainMenu1: TMainMenu;
    MenuItem1: TMenuItem;
    MenuItem2: TMenuItem;
    MenuItem3: TMenuItem;
    Scan: TAction;
    Save: TAction;
    ActionList1: TActionList;
    Memo1: TMemo;
    Panel1: TPanel;
    Splitter1: TSplitter;
    Splitter2: TSplitter;
    StatusBar1: TStatusBar;
    ToolBar1: TToolBar;
    ToolButton1: TToolButton;
    ToolButton2: TToolButton;
    procedure _onClose(Sender: TObject; var CloseAction: TCloseAction);
    procedure _onCreate(Sender: TObject);
    procedure _Save(Sender: TObject);
    procedure _Scan(Sender: TObject);
  private
    Options:TOptions;
    ScanResult:TScanResult;
  public
    procedure DummyWriteToLog(msg:string);
  end;

var
  Form1: TForm1;

implementation

{$R *.lfm}

{ TForm1 }

procedure TForm1._onCreate(Sender: TObject);
var
  tp:string;
begin
  tp:='Z:\hdd\src\fpc\lazarus-ccr\applications\cactusjukebox\';//путь к тестику
  Options._File:=tp+'source\cactusjukebox.pas';                //главный файл
  Options._Paths:=tp+'source';                                 //путь к исходникам
  Options._CompilerOptions:='-Sc';                             //"опция компилятора" разрешающая си синтаксис по типу i+=j;

  {Options._File:='E:\zcad\cad_source\zcad.pas';
  Options._Paths:='E:\zcad\cad_source\zengine/containers;E:\zcad\cad_source\zengine/styles;E:\zcad\cad_source\zengine;E:\zcad\cad_source\zengine/core;E:\zcad\cad_source\zengine/core/entities;E:\zcad\cad_source\zengine/core/drawings;E:\zcad\cad_source\zengine/fonts;E:\zcad\cad_source\zengine/zgl;E:\zcad\cad_source\zengine/zgl/drawers;E:\zcad\cad_source\zengine/misc;E:\zcad\cad_source\zengine/fileformats;E:\zcad\cad_source\other;E:\zcad\cad_source\../cad;E:\zcad\cad_source\other/uniqueinstance;E:\zcad\cad_source\autogenerated;E:\zcad\cad_source\zcad/electrotech;E:\zcad\cad_source\zcad/lclmod;E:\zcad\cad_source\zcad/commands;E:\zcad\cad_source\zcad/devicebase;E:\zcad\cad_source\zcad/gui;E:\zcad\cad_source\zcad/gui/forms;E:\zcad\cad_source\zcad/entities;E:\zcad\cad_source\zcad;E:\zcad\cad_source\zcad/gui/odjectinspector;E:\zcad\cad_source\zcad/core/undostack;E:\zcad\cad_source\zcad/register;E:\zcad\cad_source\zcad/core/drawings;E:\zcad\cad_source\zengine/core/utils;E:\zcad\cad_source\zcad/core/utils;zengine/core/objects;E:\zcad\cad_source\zcad/core;E:\zcad\cad_source\zcad/misc;E:\zcad\cad_source\other/AGraph/Graphs;E:\zcad\cad_source\other/AGraph/Attrs;E:\zcad\cad_source\other/AGraph/Math;E:\zcad\cad_source\other/AGraph/Vectors;E:\zcad\cad_source\other/AGraph/Packs';
  Options._CompilerOptions:='-Sd -FiE:\zcad\cad_source\components\zebase\ -FiE:\zcad\cad_source\autogenerated\';}

  Options.TargetOS:='linux';                                   //"опция компилятора" платфрма
  Options.TargetCPU:='i386';                                   //"опция компилятора" проц
end;

procedure TForm1._onClose(Sender: TObject; var CloseAction: TCloseAction);
begin
  if assigned(ScanResult)then FreeAndNil(ScanResult);//чистим прошлый результат
end;

procedure TForm1._Save(Sender: TObject);
begin
   Memo1.Clear;
   WriteGraph(Options,ScanResult,@DummyWriteToLog);//пишем то что унас есть в результате
end;
procedure TForm1._Scan(Sender: TObject);
begin
   Memo1.Clear;
   if assigned(ScanResult)then FreeAndNil(ScanResult);           //чистим прошлый результат
   ScanResult:=TScanResult.Create;                               //создаем новый результат
   ScanModule(Options._File,Options,ScanResult,@DummyWriteToLog);//пытаемся читать исходники
end;
procedure TForm1.DummyWriteToLog(msg:string);
begin
   Memo1.Append(msg);
end;
end.

