unit mainform;

{$mode objfpc}{$H+}

interface

uses
  LazUTF8,Classes, SysUtils, FileUtil, Forms, Controls, Graphics, Dialogs, ExtCtrls,
  ComCtrls, StdCtrls, ActnList, Menus,

  uoptions,uscaner,uscanresult,uwriter,ulpiimporter;

  type

  { TForm1 }

  TForm1 = class(TForm)
    EditMainFile: TEdit;
    EditCompilerOptions: TEdit;
    EditPaths: TEdit;
    ImportLPI: TAction;
    GDBobjinsp1: TPanel;
    LabelMainFile: TLabel;
    LabelCompilerOptions: TLabel;
    LabelPaths: TLabel;
    MainMenu1: TMainMenu;
    MenuItem1: TMenuItem;
    MenuItem2: TMenuItem;
    MenuItem3: TMenuItem;
    MenuItem4: TMenuItem;
    MenuItem5: TMenuItem;
    MenuItem6: TMenuItem;
    MenuItem7: TMenuItem;
    Scan: TAction;
    Save: TAction;
    ActionList1: TActionList;
    Memo1: TMemo;
    Panel1: TPanel;
    Splitter1: TSplitter;
    Splitter2: TSplitter;
    StatusBar1: TStatusBar;
    ToolBar1: TToolBar;
    ToolButton1: TToolButton;
    ToolButton2: TToolButton;
    ToolButton3: TToolButton;
    procedure _ImportLPI(Sender: TObject);
    procedure _onClose(Sender: TObject; var CloseAction: TCloseAction);
    procedure _onCreate(Sender: TObject);
    procedure _Save(Sender: TObject);
    procedure _Scan(Sender: TObject);
    procedure _SetOptionFromUI(Sender: TObject);
    procedure _SetUIFromOption(Sender: TObject);
  private
    Options:TOptions;
    ScanResult:TScanResult;
  public
    procedure DummyWriteToLog(msg:string);
  end;

var
  Form1: TForm1;

implementation

{$R *.lfm}

{ TForm1 }
procedure TForm1._SetOptionFromUI(Sender: TObject);
begin
   Options._CompilerOptions:=EditCompilerOptions.Text;
   Options._File:=EditMainFile.Text;
   Options._Paths:=EditPaths.Text;
end;
procedure TForm1._SetUIFromOption(Sender: TObject);
begin
   EditCompilerOptions.Text:=Options._CompilerOptions;
   EditMainFile.Text:=Options._File;
   EditPaths.Text:=Options._Paths;
end;
procedure TForm1._onCreate(Sender: TObject);
{var
  tp:string;}
begin
   Options._File:='?? import or edit this';                //главный файл
   Options._Paths:='?? import or edit this';               //путь к исходникам
   Options._CompilerOptions:='-Sc';
  {tp:='Z:\hdd\src\fpc\lazarus-ccr\applications\cactusjukebox\';//путь к тестику
  Options._File:=tp+'source\cactusjukebox.pas';                //главный файл
  Options._Paths:=tp+'source';                                 //путь к исходникам
  Options._CompilerOptions:='-Sc';}                             //"опция компилятора" разрешающая си синтаксис по типу i+=j;

  {Options._File:='E:\zcad\cad_source\zcad.pas';
  Options._Paths:='E:\zcad\cad_source\zengine/containers;E:\zcad\cad_source\zengine/styles;E:\zcad\cad_source\zengine;E:\zcad\cad_source\zengine/core;E:\zcad\cad_source\zengine/core/entities;E:\zcad\cad_source\zengine/core/drawings;E:\zcad\cad_source\zengine/fonts;E:\zcad\cad_source\zengine/zgl;E:\zcad\cad_source\zengine/zgl/drawers;E:\zcad\cad_source\zengine/misc;E:\zcad\cad_source\zengine/fileformats;E:\zcad\cad_source\other;E:\zcad\cad_source\../cad;E:\zcad\cad_source\other/uniqueinstance;E:\zcad\cad_source\autogenerated;E:\zcad\cad_source\zcad/electrotech;E:\zcad\cad_source\zcad/lclmod;E:\zcad\cad_source\zcad/commands;E:\zcad\cad_source\zcad/devicebase;E:\zcad\cad_source\zcad/gui;E:\zcad\cad_source\zcad/gui/forms;E:\zcad\cad_source\zcad/entities;E:\zcad\cad_source\zcad;E:\zcad\cad_source\zcad/gui/odjectinspector;E:\zcad\cad_source\zcad/core/undostack;E:\zcad\cad_source\zcad/register;E:\zcad\cad_source\zcad/core/drawings;E:\zcad\cad_source\zengine/core/utils;E:\zcad\cad_source\zcad/core/utils;zengine/core/objects;E:\zcad\cad_source\zcad/core;E:\zcad\cad_source\zcad/misc;E:\zcad\cad_source\other/AGraph/Graphs;E:\zcad\cad_source\other/AGraph/Attrs;E:\zcad\cad_source\other/AGraph/Math;E:\zcad\cad_source\other/AGraph/Vectors;E:\zcad\cad_source\other/AGraph/Packs';
  Options._CompilerOptions:='-Sd -FiE:\zcad\cad_source\components\zebase\ -FiE:\zcad\cad_source\autogenerated\';}

  Options.TargetOS:='linux';                                   //"опция компилятора" платфрма
  Options.TargetCPU:='i386';                                   //"опция компилятора" проц
  _SetUIFromOption(nil);
end;

procedure TForm1._onClose(Sender: TObject; var CloseAction: TCloseAction);
begin
  if assigned(ScanResult)then FreeAndNil(ScanResult);//чистим прошлый результат
end;

procedure TForm1._ImportLPI(Sender: TObject);
var
  od:TOpenDialog;
begin
   od:=TOpenDialog.Create(nil);
   od.Title:='Import Lazarus project file';
   od.Filter:='Lazarus project files (*.lpi)|*.lpi|All files (*.*)|*.*';
   od.DefaultExt:='lpi';
   od.FilterIndex := 1;
   if od.Execute then
   begin
     LPIImport(Options,od.FileName,@DummyWriteToLog);
   end;
   od.Free;
   _SetUIFromOption(nil);
end;

procedure TForm1._Save(Sender: TObject);
begin
   Memo1.Clear;
   WriteGraph(Options,ScanResult,@DummyWriteToLog);//пишем то что унас есть в результате
end;
procedure TForm1._Scan(Sender: TObject);
begin
   Memo1.Clear;
   if assigned(ScanResult)then FreeAndNil(ScanResult);           //чистим прошлый результат
   ScanResult:=TScanResult.Create;                               //создаем новый результат
   ScanModule(Options._File,Options,ScanResult,@DummyWriteToLog);//пытаемся читать исходники
end;
procedure TForm1.DummyWriteToLog(msg:string);
begin
   Memo1.Append(msg);
end;
end.

