//---------------------------------------------------------------------------

#include <vcl.h>
#pragma hdrstop
USERES("pkVector.res");
USEPACKAGE("vcl50.bpi");
USEUNIT("..\Vectors\Aliasm.pas");
USEUNIT("..\Vectors\Aliasv.pas");
USEUNIT("..\Vectors\Base16v.pas");
USEUNIT("..\Vectors\Base32v.pas");
USEUNIT("..\Vectors\Base64v.pas");
USEUNIT("..\Vectors\Base80v.pas");
USEUNIT("..\Vectors\Base8v.pas");
USEUNIT("..\Vectors\Boolm.pas");
USEUNIT("..\Vectors\Boolv.pas");
USEUNIT("..\Vectors\ChckFree.pas");
USEUNIT("..\Vectors\CheckCPU.pas");
USEUNIT("..\Vectors\Crc16.pas");
USEUNIT("..\Vectors\Crc32.pas");
USEUNIT("..\Vectors\ExtSys.pas");
USEUNIT("..\Vectors\ExtType.pas");
USEUNIT("..\Vectors\F_PQueue.pas");
USEUNIT("..\Vectors\F32g.pas");
USEUNIT("..\Vectors\F32m.pas");
USEUNIT("..\Vectors\F32sv.pas");
USEUNIT("..\Vectors\F32v.pas");
USEUNIT("..\Vectors\F64g.pas");
USEUNIT("..\Vectors\F64m.pas");
USEUNIT("..\Vectors\F64sv.pas");
USEUNIT("..\Vectors\F64v.pas");
USEUNIT("..\Vectors\F80g.pas");
USEUNIT("..\Vectors\F80m.pas");
USEUNIT("..\Vectors\F80sv.pas");
USEUNIT("..\Vectors\F80v.pas");
USEUNIT("..\Vectors\II64Dic.pas");
USEUNIT("..\Vectors\IIDic.pas");
USEUNIT("..\Vectors\Indexsv.pas");
USEUNIT("..\Vectors\Indexv.pas");
USEUNIT("..\Vectors\Int16g.pas");
USEUNIT("..\Vectors\Int16m.pas");
USEUNIT("..\Vectors\Int16sv.pas");
USEUNIT("..\Vectors\Int16v.pas");
USEUNIT("..\Vectors\Int32g.pas");
USEUNIT("..\Vectors\Int32m.pas");
USEUNIT("..\Vectors\Int32sv.pas");
USEUNIT("..\Vectors\Int32v.pas");
USEUNIT("..\Vectors\Int64g.pas");
USEUNIT("..\Vectors\Int64m.pas");
USEUNIT("..\Vectors\Int64sv.pas");
USEUNIT("..\Vectors\Int64v.pas");
USEUNIT("..\Vectors\Int8g.pas");
USEUNIT("..\Vectors\Int8m.pas");
USEUNIT("..\Vectors\Int8sv.pas");
USEUNIT("..\Vectors\Int8v.pas");
USEUNIT("..\Vectors\IPDic.pas");
USEUNIT("..\Vectors\IQueue.pas");
USEUNIT("..\Vectors\ISDic.pas");
USEUNIT("..\Vectors\IStack.pas");
USEUNIT("..\Vectors\LogFile.pas");
USEUNIT("..\Vectors\MultiLst.pas");
USEUNIT("..\Vectors\NLSTypes.pas");
USEUNIT("..\Vectors\ParseCmd.pas");
USEUNIT("..\Vectors\ParseWideCmd.pas");
USEUNIT("..\Vectors\Pointerv.pas");
USEUNIT("..\Vectors\PQueue.pas");
USEUNIT("..\Vectors\PStack.pas");
USEUNIT("..\Vectors\RBTree.pas");
USEUNIT("..\Vectors\SIDic.pas");
USEUNIT("..\Vectors\SIQueue.pas");
USEUNIT("..\Vectors\SPDic.pas");
USEUNIT("..\Vectors\SQueue.pas");
USEUNIT("..\Vectors\SSDic.pas");
USEUNIT("..\Vectors\StrCount.pas");
USEUNIT("..\Vectors\StrLst.pas");
USEUNIT("..\Vectors\UInt16g.pas");
USEUNIT("..\Vectors\UInt16m.pas");
USEUNIT("..\Vectors\UInt16sv.pas");
USEUNIT("..\Vectors\UInt16v.pas");
USEUNIT("..\Vectors\UInt32g.pas");
USEUNIT("..\Vectors\UInt32m.pas");
USEUNIT("..\Vectors\UInt32sv.pas");
USEUNIT("..\Vectors\UInt32v.pas");
USEUNIT("..\Vectors\UInt8g.pas");
USEUNIT("..\Vectors\UInt8m.pas");
USEUNIT("..\Vectors\UInt8sv.pas");
USEUNIT("..\Vectors\UInt8v.pas");
USEUNIT("..\Vectors\VCLCmpt.pas");
USEUNIT("..\Vectors\VComUtil.pas");
USEUNIT("..\Vectors\VectErr.pas");
USEUNIT("..\Vectors\Vectors.pas");
USEUNIT("..\Vectors\VectProc.pas");
USEUNIT("..\Vectors\VectStr.pas");
USEUNIT("..\Vectors\VFileSys.pas");
USEUNIT("..\Vectors\VFormat.pas");
USEUNIT("..\Vectors\VFStream.pas");
USEUNIT("..\Vectors\VFStrm64.pas");
USEUNIT("..\Vectors\VFstTmr.pas");
USEUNIT("..\Vectors\VMapStrm.pas");
USEUNIT("..\Vectors\VOleStrm.pas");
USEUNIT("..\Vectors\VStream.pas");
USEUNIT("..\Vectors\VStrm64.pas");
USEUNIT("..\Vectors\VTxtStrm.pas");
USEUNIT("..\Vectors\VUnicode.pas");
USEUNIT("..\Vectors\VWideStr.pas");
USEUNIT("..\Vectors\VWinUtil.pas");
USEUNIT("..\Vectors\WFileSys.pas");
USEUNIT("..\Vectors\WSPDic.pas");
USEUNIT("..\Vectors\WSPDicFast.pas");
USEUNIT("..\Vectors\WSSDic.pas");
USEUNIT("..\Vectors\WStrLst.pas");
USEUNIT("..\Vectors\VStrmCrc.pas");
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------
