PGDBControlPointArray=^GDBControlPointArray;
OpenArray=object(GDBaseObject)
                PArray:GDBPointer;
                Count,Max,Size:GDBInteger;
                procedure resize;virtual;abstract;
          end;
GDBOpenArray=object(OpenArray)
                      procedure add(p:GDBPointer);virtual;abstract;
             end;
PGDBLayerArray=^GDBLayerArray;
GDBLayerArray=object(GDBOpenArray)
                    procedure clear;virtual;abstract;
                    function addlayer(name:GDBString;color:GDBInteger;lw:GDBInteger):GDBInteger;virtual;abstract;
              end;
PGDBPoint2DArray=^GDBPoint2DArray;
GDBPoint2DArray=object(GDBOpenArray)
                      procedure DrawGeometry;virtual;abstract;
                      function inrect:GDBBoolean;virtual;abstract;
                end;
PGDBOOutbound2DIArray=^GDBOOutbound2DIArray;
GDBOOutbound2DIArray=object(GDBOpenArray)
                      procedure DrawGeometry;virtual;abstract;
                      procedure addpoint(point:GDBvertex2DI);virtual;abstract;
                      procedure addlastpoint(point:GDBvertex2DI);virtual;abstract;
                      procedure addgdbvertex(point:GDBvertex);virtual;abstract;
                      procedure addlastgdbvertex(point:GDBvertex);virtual;abstract;
                      procedure clear;virtual;abstract;
                      function onmouse:GDBInteger;virtual;abstract;
                      function inrect:GDBBoolean;virtual;abstract;
                      function perimetr:GDBDouble;virtual;abstract;
                end;
PSelectedObjDesc=^SelectedObjDesc;
GDBVisualProp=record
                    ID,Layer:GDBWord;
                    LineWeight:GDBSmallint;
              end;
PGDBObjEntity=^GDBObjEntity;
GDBObjEntity=object(GDBaseObject)
                    vp:GDBVisualProp;
                    Selected,Visible:GDBBoolean;
                    infrustum:GDBBoolean;
                    procedure SaveToDXF(var handle:longint; outhandle: GDBInteger);virtual;abstract;
                    procedure Format;virtual;abstract;
                    procedure DrawWithAttrib(owner:PGDBObjEntity);virtual;abstract;
                    procedure DrawGeometry;virtual;abstract;
                    procedure RenderFeedback;virtual;abstract;
                    procedure 56RenderOsnap;virtual;abstract;
                    function getosnappoint(ostype:GDBFloat):gdbvertex;virtual;abstract;
                    procedure FeedbackDraw;virtual;abstract;
                    function CalculateLineWeight(owner:PGDBObjEntity):GDBInteger;virtual;abstract;
                    procedure feedbackinrect;virtual;abstract;
                    function Clone:PGDBObjEntity;virtual;abstract;
                    procedure rtedit(refp:GDBPointer;mode:GDBFloat;dist,wc:gdbvertex);virtual;abstract;
                    procedure rtsave(refp:GDBPointer);virtual;abstract;
                    destructor done;virtual;abstract;
                    procedure TransformAt(p:GDBPointer;dist:gdbvertex);virtual;abstract;
                    procedure getoutbound;virtual;abstract;
                    procedure calcvisible;virtual;abstract;
                    function onmouse:GDBBoolean;virtual;abstract;
                    procedure startsnap;virtual;abstract;
                    function getsnap(var osp:os_record):GDBBoolean;virtual;abstract;
                    function getintersect(var osp:os_record;pobj:PGDBObjEntity):GDBBoolean;virtual;abstract;
                    procedure higlight;virtual;abstract;
										procedure addcontrolpoints(tdesc:pselectedobjdesc);virtual;abstract;
                    procedure select;virtual;abstract;
                    procedure remapcontrolpoints(pp:PGDBControlPointArray);virtual;abstract;
                    procedure rtmodify(md:PSelectedObjDesc;dist,wc:gdbvertex;save:GDBBoolean);virtual;abstract;
                    procedure rtmodifyonepoint(point:pcontrolpointdesc;tobj:PGDBObjEntity;dist,wc:gdbvertex;ptdata:GDBPointer);virtual;abstract;
                    procedure remaponecontrolpoint(pdesc:pcontrolpointdesc);virtual;abstract;
                    function beforertmodify:GDBPointer;virtual;abstract;
                    procedure afterrtmodify(p:GDBPointer);virtual;abstract;
                    function CalcCompactMemSize:longint;virtual;abstract;
                    function SaveToCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
                    function LoadCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
              end;
PGDBObjEntityArray=^GDBObjEntityArray;
GDBObjEntityArray=array [0..0] of PGDBObjEntity;
PGDBObjEntityOpenArray=^GDBObjEntityOpenArray;
GDBObjEntityOpenArray=object(OpenArray)
                      procedure DrawAll(owner:PGDBObjEntity);virtual;abstract;
                      function CreateObj(t:GDBByte):PGDBObjEntity;virtual;abstract;
                      function add(p:GDBPointer):GDBInteger;virtual;abstract;
                      procedure renderfeedbac;virtual;abstract;
                      procedure 56RenderOsnap;virtual;abstract;
                      procedure calcvisible;virtual;abstract;
                      procedure cleareraseobj;virtual;abstract;
                      function CalcCopactMemSize(var objcount:GDBInteger):longint;virtual;abstract;
                      function SaveToCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
                      function LoadCompactMemSize(var pmem:GDBPointer;objcount:GDBInteger):GDBInteger;virtual;abstract;
                      function CreateInitObj(t:GDBByte):PGDBObjEntity;virtual;abstract;
                end;
GDBObj3d=object(GDBObjEntity)
         end;
PGDBObj2dprop=^GDBObj2dprop;
GDBObj2dprop=record
                   OX,OY,OZ:GDBvertex;
                   P_insert:GDBvertex;
             end;
GDBObj2d=object(GDBObjEntity)
               ObjMatrix:DMatrix4D;
               Local:GDBObj2dprop;
               ProjP_insert:GDBvertex;
               pprojoutbound:PGDBOOutbound2DIArray;
               lod:GDBByte;
               procedure CalcObjMatrix;virtual;abstract;
               function CalcCompactMemSize:longint;virtual;abstract;
               function SaveToCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
               function LoadCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
         end;
PGDBObjPoint=^GDBObjPoint;
GDBObjPoint=object(GDBObj3d)
                 P_insert:GDBvertex;
                 ProjPoint:GDBvertex;
                 procedure DrawGeometry;virtual;abstract;
                 procedure 56RenderOsnap;virtual;abstract;
                 function getosnappoint(ostype:GDBFloat):gdbvertex;virtual;abstract;
                 procedure calcvisible;virtual;abstract;
                 procedure RenderFeedback;virtual;abstract;
                 function getsnap(var osp:os_record):GDBBoolean;virtual;abstract;
                 function onmouse:GDBBoolean;virtual;abstract;
                 procedure feedbackinrect;virtual;abstract;
                 procedure addcontrolpoints(tdesc:pselectedobjdesc);virtual;abstract;
                 procedure remaponecontrolpoint(pdesc:pcontrolpointdesc);virtual;abstract;
                 procedure rtmodifyonepoint(point:pcontrolpointdesc;tobj:PGDBObjEntity;dist,wc:gdbvertex;ptdata:GDBPointer);virtual;abstract;
                 function Clone:PGDBObjEntity;virtual;abstract;
                 procedure rtsave(refp:GDBPointer);virtual;abstract;
                 function CalcCompactMemSize:longint;virtual;abstract;
                 function SaveToCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
                 function LoadCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
           end;
PGDBLineProp=^GDBLineProp;
GDBLineProp=record
                  lBegin,lEnd:GDBvertex;
              end;
PGDBObjLine=^GDBObjLine;
GDBObjLine=object(GDBObj3d)
                 Coord:GDBLineProp;
                 l_1_4,l_1_3,l_1_2,l_2_3,l_3_4:GDBvertex;
                 PProjPoint:PGDBLineProj;
                 length:GDBDouble;
                 dir:GDBvertex;
                 pdx,pdy:GDBDouble;
                 length_2:GDBDouble;
                 procedure SaveToDXF(var handle:longint; outhandle: GDBInteger);virtual;abstract;
                 procedure Format;virtual;abstract;
                 procedure DrawGeometry;virtual;abstract;
                 procedure RenderFeedback;virtual;abstract;
                 function Clone:PGDBObjEntity;virtual;abstract;
                 procedure rtedit(refp:GDBPointer;mode:GDBFloat;dist,wc:gdbvertex);virtual;abstract;
                 procedure rtsave(refp:GDBPointer);virtual;abstract;
                 procedure calcvisible;virtual;abstract;
                 procedure TransformAt(p:GDBPointer;dist:gdbvertex);virtual;abstract;
                 function onmouse:GDBBoolean;virtual;abstract;
                 procedure feedbackinrect;virtual;abstract;
                 function getsnap(var osp:os_record):GDBBoolean;virtual;abstract;
                 function getintersect(var osp:os_record;pobj:PGDBObjEntity):GDBBoolean;virtual;abstract;
                 destructor done;virtual;abstract;
                 procedure addcontrolpoints(tdesc:pselectedobjdesc);virtual;abstract;
                 function beforertmodify:GDBPointer;virtual;abstract;
                 procedure rtmodifyonepoint(point:pcontrolpointdesc;tobj:PGDBObjEntity;dist,wc:gdbvertex;ptdata:GDBPointer);virtual;abstract;
                 procedure remaponecontrolpoint(pdesc:pcontrolpointdesc);virtual;abstract;
                 function CalcCompactMemSize:longint;virtual;abstract;
                 function SaveToCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
                 function LoadCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
           end;
PGDBTextProp=^GDBTextProp;
GDBTextProp=record
                  size,oblique,wfactor,angle:GDBDouble;
                  justify:GDBByte;
            end;
PGDBObjText=^GDBObjText;
GDBObjText=object(GDBObj2d)
                 Content:GDBString;
                 DrawMatrix:DMatrix4D;
                 P_draw:GDBvertex;
                 textprop:GDBTextProp;
                 PPoint,PProjPoint:PGDBPoint2DArray;
                 CoordMin,CoordMax:GDBvertex;
                 Outbound:OutBound4V;
                 obj_height,obj_width,obj_y:GDBDouble;
                 procedure CalcObjMatrix;virtual;abstract;
                 procedure CalcGabarit;virtual;abstract;
                 procedure SaveToDXF(var handle:longint; outhandle: GDBInteger);virtual;abstract;
                 procedure Format;virtual;abstract;
                 procedure DrawGeometry;virtual;abstract;
                 procedure RenderFeedback;virtual;abstract;
                 function Clone:PGDBObjEntity;virtual;abstract;
                 procedure rtedit(refp:GDBPointer;mode:GDBFloat;dist,wc:gdbvertex);virtual;abstract;
                 procedure rtsave(refp:GDBPointer);virtual;abstract;
                 procedure createpoint;virtual;abstract;
                 procedure projectpoint;virtual;abstract;
                 procedure getoutbound;virtual;abstract;
                 procedure calcvisible;virtual;abstract;
                 destructor done;virtual;abstract;
                 function onmouse:GDBBoolean;virtual;abstract;
                 procedure feedbackinrect;virtual;abstract;
                 procedure TransformAt(p:GDBPointer;dist:gdbvertex);virtual;abstract;
                 function getsnap(var osp:os_record):GDBBoolean;virtual;abstract;
                 procedure addcontrolpoints(tdesc:pselectedobjdesc);virtual;abstract;
                 procedure remaponecontrolpoint(pdesc:pcontrolpointdesc);virtual;abstract;
                 procedure rtmodifyonepoint(point:pcontrolpointdesc;tobj:PGDBObjEntity;dist,wc:gdbvertex;ptdata:GDBPointer);virtual;abstract;
                 function CalcCompactMemSize:longint;virtual;abstract;
                 function SaveToCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
                 function LoadCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
           end;
PGDBObjMText=^GDBObjMText;
GDBObjMText=object(GDBObjText)
                 width,linespace:GDBDouble;
                 ptext:PGDBOpenArrayGDBString_GDBWord;
                 procedure SaveToDXF(var handle:longint; outhandle: GDBInteger);virtual;abstract;
                 procedure Format;virtual;abstract;
                 procedure DrawGeometry;virtual;abstract;
                 function CalcCompactMemSize:longint;virtual;abstract;
                 function SaveToCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
                 function LoadCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
            end;
PGDBObjArc=^GDBObjARC;
GDBObjArc=object(GDBObj2d)
                 R,StartAngle,EndAngle,angle:GDBDouble;
                 PProjPoint,PPoint:PGDBPoint2DArray;
                 length:GDBDouble;
                 q0,q1,q2:GDBvertex;
                 pq0,pq1,pq2:GDBvertex;
                 Outbound:OutBound4V;
                 procedure SaveToDXF(var handle:longint; outhandle: GDBInteger);virtual;abstract;
                 procedure DrawGeometry;virtual;abstract;
                 procedure addcontrolpoints(tdesc:pselectedobjdesc);virtual;abstract;
                 procedure remaponecontrolpoint(pdesc:pcontrolpointdesc);virtual;abstract;
                 procedure CalcObjMatrix;virtual;abstract;
                 procedure Format;virtual;abstract;
                 procedure createpoint;virtual;abstract;
                 procedure getoutbound;virtual;abstract;
                 procedure RenderFeedback;virtual;abstract;
                 procedure projectpoint;virtual;abstract;
                 function onmouse:GDBBoolean;virtual;abstract;
                 function getsnap(var osp:os_record):GDBBoolean;virtual;abstract;
                 function beforertmodify:GDBPointer;virtual;abstract;
                 procedure rtmodifyonepoint(point:pcontrolpointdesc;tobj:PGDBObjEntity;dist,wc:gdbvertex;ptdata:GDBPointer);virtual;abstract;
                 function Clone:PGDBObjEntity;virtual;abstract;
                 procedure rtsave(refp:GDBPointer);virtual;abstract;
                 function CalcCompactMemSize:longint;virtual;abstract;
                 function SaveToCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
                 function LoadCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
           end;
PGDBObjCircle=^GDBObjCircle;
GDBObjCircle=object(GDBObj2d)
                 R:GDBDouble;
                 q0,q1,q2,q3:GDBvertex;
                 pq0,pq1,pq2,pq3:GDBvertex;
                 length:GDBDouble;
                 Outbound:OutBound4V;
                 PProjPoint:PGDBPoint2DArray;
                 procedure CalcObjMatrix;virtual;abstract;
                 procedure calcvisible;virtual;abstract;
                 procedure RenderFeedback;virtual;abstract;
                 procedure getoutbound;virtual;abstract;
                 procedure SaveToDXF(var handle:longint; outhandle: GDBInteger);virtual;abstract;
                 procedure Format;virtual;abstract;
                 procedure DrawGeometry;virtual;abstract;
                 function Clone:PGDBObjEntity;virtual;abstract;
                 procedure rtedit(refp:GDBPointer;mode:GDBFloat;dist,wc:gdbvertex);virtual;abstract;
                 procedure rtsave(refp:GDBPointer);virtual;abstract;
                 procedure TransformAt(p:GDBPointer;dist:gdbvertex);virtual;abstract;
                 procedure createpoint;virtual;abstract;
                 procedure projectpoint;virtual;abstract;
                 function onmouse:GDBBoolean;virtual;abstract;
                 procedure higlight;virtual;abstract;
                 function getsnap(var osp:os_record):GDBBoolean;virtual;abstract;
                 procedure feedbackinrect;virtual;abstract;
                 procedure addcontrolpoints(tdesc:pselectedobjdesc);virtual;abstract;
                 procedure remaponecontrolpoint(pdesc:pcontrolpointdesc);virtual;abstract;
                 function beforertmodify:GDBPointer;virtual;abstract;
                 procedure rtmodifyonepoint(point:pcontrolpointdesc;tobj:PGDBObjEntity;dist,wc:gdbvertex;ptdata:GDBPointer);virtual;abstract;
                 function CalcCompactMemSize:longint;virtual;abstract;
                 function SaveToCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
                 function LoadCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
           end;
PGDBObjPolyline=^GDBObjPolyline;
GDBObjPolyline=object(GDBObj3d)
                 closed:GDBBoolean;
                 vertexarray:GDBOpenArray;
                 snaparray:PVectotSnapArray;
                 procedure SaveToDXF(var handle:longint; outhandle: GDBInteger);virtual;abstract;
                 procedure Format;virtual;abstract;
                 procedure DrawGeometry;virtual;abstract;
                 function getosnappoint(ostype:GDBFloat):gdbvertex;virtual;abstract;
                 procedure 56RenderOsnap;virtual;abstract;
                 procedure AddControlpoint(pcp:popenarrayobjcontrolpoint_GDBWordwm;objnum:GDBInteger);virtual;abstract;
                 function Clone:PGDBObjEntity;virtual;abstract;
                 procedure rtedit(refp:GDBPointer;mode:GDBFloat;dist,wc:gdbvertex);virtual;abstract;
                 procedure rtsave(refp:GDBPointer);virtual;abstract;
                 function CalcCompactMemSize:longint;virtual;abstract;
                 function SaveToCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
                 function LoadCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
           end;
PGDBObjLWPolyline=^GDBObjLWpolyline;
GDBObjLWPolyline=object(GDBObj2d)
                 closed:GDBBoolean;
                 vertexarray:GDBOpenArray;
                 normalarray:GDBOpenArray;
                 widtharray:GDBOpenArray;
                 procedure SaveToDXF(var handle:longint; outhandle: GDBInteger);virtual;abstract;
                 procedure DrawGeometry;virtual;abstract;
                 procedure reformat;virtual;abstract;
                 function CalcCompactMemSize:longint;virtual;abstract;
                 function SaveToCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
                 function LoadCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
           end;
PGDBObjBlockdef=^GDBObjBlockdef;
GDBObjBlockdef=object(GDBaseObject)
                     Name:GDBString;
                     Base:GDBvertex;
                     Entities:GDBObjEntityOpenArray;
               end;
BlockdefArray=array [0..0] of GDBObjBlockdef;
PBlockdefArray=^BlockdefArray;
GDBObjBlockdefArray=object(OpenArray)
                      procedure add(p:GDBPointer);virtual;abstract;
                      function getindex(name:GDBString):GDBInteger;virtual;abstract;
                      function loadblock(name:GDBString):GDBInteger;virtual;abstract;
                      function create(name:GDBString):PGDBObjBlockdef;virtual;abstract;
                    end;
PGDBObjBlockInsert=^GDBObjBlockInsert;
GDBObjBlockInsert=object(GDBObj2d)
                     scale:GDBvertex;
                     rotate:GDBDouble;
                     index:GDBInteger;
                     Name:GDBString;
                     pattrib:GDBPointer;
                     procedure DrawGeometry;virtual;abstract;
                     procedure Format;virtual;abstract;
                     procedure 56RenderOsnap;virtual;abstract;
                     function getosnappoint(ostype:GDBFloat):gdbvertex;virtual;abstract;
                     function Clone:PGDBObjEntity;virtual;abstract;
                     procedure rtedit(refp:GDBPointer;mode:GDBFloat;dist,wc:gdbvertex);virtual;abstract;
                     procedure rtsave(refp:GDBPointer);virtual;abstract;
                     destructor done;virtual;abstract;
                     function CalcCompactMemSize:longint;virtual;abstract;
                     function SaveToCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
                     function LoadCompactMemSize(var pmem:GDBPointer):longint;virtual;abstract;
                  end;
GDBControlPointArray=object(GDBOpenArray)
                           SelectedCount:GDBInteger;
                           destructor done;virtual;abstract;
                           procedure draw;virtual;abstract;
                           procedure getnearesttomouse(var td:tcontrolpointdist);virtual;abstract;
                           procedure selectcurrentcontrolpoint(key:GDBByte);virtual;abstract;
                     end;
SelectedObjDesc=record
                      objaddr:PGDBObjEntity;
                      pcontrolpoint:PGDBControlPointArray;
                      ptempobj:PGDBObjEntity;
                end;
GDBSelectedObjArray=object(GDBOpenArray)
                          SelectedCount:GDBInteger;
                          function addobject(objnum:PGDBObjEntity):pselectedobjdesc;virtual;abstract;
                          procedure clearallobjects;virtual;abstract;
                          procedure remappoints;virtual;abstract;
                          procedure draw;virtual;abstract;
                          function getnearesttomouse:tcontrolpointdist;virtual;abstract;
                          procedure selectcurrentcontrolpoint(key:GDBByte);virtual;abstract;
                          destructor done;virtual;abstract;
                          procedure modifyobj(dist,wc:gdbvertex;save:GDBBoolean);virtual;abstract;
                          procedure drawobj;virtual;abstract;
                    end;
GDBDescriptor=record
    LayerTable:GDBLayerArray;
    BlockDefArray:GDBObjBlockdefArray;
    ObjArray:GDBObjEntityOpenArray;
    ConstructObjRoot:GDBObjEntityOpenArray;
    SelObjArray:GDBSelectedObjArray;
end;
PGDBDescriptor=^GDBDescriptor;

