CD /D "%~dp0"
del /S /Q ..\cad\*.*
rd /S /Q ..\cad\autosave
rd /S /Q ..\cad\blocks
rd /S /Q ..\cad\components
rd /S /Q ..\cad\fonts
rd /S /Q ..\cad\images
rd /S /Q ..\cad\languages
rd /S /Q ..\cad\log
rd /S /Q ..\cad\menu
rd /S /Q ..\cad\plugins
rd /S /Q ..\cad\programdb
rd /S /Q ..\cad\rtl
rd /S /Q ..\cad\sample
rd /S /Q ..\cad\template
rd /S /Q ..\cad\utils
del /S /Q ..\lib\*.*
md ..\cad
md ..\cad_source\autogenerated
xcopy /y /E runtimefiles\common\* ..\cad 
xcopy /y /E runtimefiles\zcadelectrotech\* ..\cad 
xcopy /y /E runtimefiles\restricted\* ..\cad 
del /S /Q ..\cad_source\autogenerated\*.*
typeexporter\typeexporter.exe pathprefix=../cad_source/ outputfile=../cad/rtl/system.pas processfiles=typeexporter\zcad.files;typeexporter\zcadelectrotech.files
echo {$DEFINE ELECTROTECH}>..\cad_source\autogenerated\buildmode.inc