.PHONY: crutch_bfore_compilation
default: crutch_bfore_compilation

crutch_bfore_compilation:                  
	@echo Makefile.crutch_bfore_compilation(5,1) Note: Workaround for https://gitlab.com/freepascal.org/fpc/source/-/issues/39387
	rm -rf ../lib/x86_64-win64/uzeparser.*
	rm -rf ../lib/i386-win32/uzeparser.*
	rm -rf ../lib/x86_64-linux/uzeparser.*
	rm -rf ../lib/i386-linux/uzeparser.*