unit savedvar;
interface
uses System;
var
  DMenuX:GDBInteger;
  DMenuY:GDBInteger;
  TEdWND_Left:GDBInteger;
  TEdWND_Top:GDBInteger;
  TEdWND_Width:GDBInteger;
  TEdWND_Height:GDBInteger;
  VIEW_CommandLineH:GDBInteger;
  VIEW_ObjInspV:GDBInteger;
  VIEW_ObjInspSubV:GDBInteger;
  PATH_File0:GDBString;
  PATH_File1:GDBString;
  PATH_File2:GDBString;
  PATH_File3:GDBString;
  PATH_File4:GDBString;
  PATH_File5:GDBString;
  PATH_File6:GDBString;
  PATH_File7:GDBString;
  PATH_File8:GDBString;
  PATH_File9:GDBString;
implementation
begin
  DMenuX:=334;
  DMenuY:=101;
  TEdWND_Left:=495;
  TEdWND_Top:=197;
  TEdWND_Width:=570;
  TEdWND_Height:=483;
  VIEW_CommandLineH:=65;
  VIEW_ObjInspV:=307;
  VIEW_ObjInspSubV:=141;
  PATH_File0:='C:\zcad\cad\sample\test_dxf\em.dxf';
  PATH_File1:='C:\zcad\cad\autosave\autosave.dxf';
  PATH_File2:='C:\zcad\cad\sample\test_dxf\ops.dxf';
  PATH_File3:='C:\zcad\cad\sample\test_dxf\teapot.dxf';
  PATH_File4:='H:\nh\Зварыгина\стоянка\proj CO.dxf';
  PATH_File5:='H:\nh\Зварыгина\стоянка\co.dxf';
  PATH_File6:='H:\nh\Коробова\Муравленко\парковка\proj.dxf';
  PATH_File7:='/mnt/win_c/zcad/cad/sample/test_dxf/em.dxf';
  PATH_File8:='Z:\cad\autosave\autosave.dxf';
  PATH_File9:='J:\nh\Коробова\Муравленко\парковка\proj.dxf';
end.