unit savedvar;
interface
uses System;
var
  DMenuX:GDBInteger;
  DMenuY:GDBInteger;
  TEdWND_Left:GDBInteger;
  TEdWND_Top:GDBInteger;
  TEdWND_Width:GDBInteger;
  TEdWND_Height:GDBInteger;
  VIEW_CommandLineH:GDBInteger;
  VIEW_ObjInspV:GDBInteger;
  VIEW_ObjInspSubV:GDBInteger;
  PATH_File0:GDBString;
  PATH_File1:GDBString;
  PATH_File2:GDBString;
  PATH_File3:GDBString;
  PATH_File4:GDBString;
  PATH_File5:GDBString;
  PATH_File6:GDBString;
  PATH_File7:GDBString;
  PATH_File8:GDBString;
  PATH_File9:GDBString;
implementation
begin
  DMenuX:=503;
  DMenuY:=171;
  TEdWND_Left:=504;
  TEdWND_Top:=267;
  TEdWND_Width:=794;
  TEdWND_Height:=481;
  VIEW_CommandLineH:=65;
  VIEW_ObjInspV:=238;
  VIEW_ObjInspSubV:=95;
  PATH_File0:='C:\zcad\cad\autosave\autosave.dxf';
  PATH_File1:='C:\zcad\cad\sample\test_dxf\ops.dxf';
  PATH_File2:='C:\zcad\cad\sample\test_dxf\em.dxf';
  PATH_File3:='J:\nh\Алферов\тбменьбройлер\OPS.dxf';
  PATH_File4:='D:\Stas\original1.dxf';
  PATH_File5:='C:\zcad\cad\sample\test_dxf\teapot.dxf';
  PATH_File6:='J:\nh\Коробова\Голышева\proj.dxf';
  PATH_File7:='J:\nh\Коробова\Рижская\proj.dxf';
  PATH_File8:='J:\nh\Коробова\Олимпийская\proj.dxf';
  PATH_File9:='J:\nh\Фарит\Свалка\Утилизация\proj.dxf';
end.