UNIT uDxTypes;

INTERFACE

uses
  Windows;

{$ALIGN ON}
{$MINENUMSIZE 4}

type
  FLOAT = Single;
  _FLOAT = Single;
  LP_FLOAT = ^FLOAT;
  _FLOAT_ARRAY = array[0..65535] of FLOAT;
  LP_FLOAT_ARRAY = ^_FLOAT_ARRAY;


  LP_BOOL = ^BOOL;
  _BOOL_ARRAY = array[0..65535] of BOOL;
  LP_BOOL_ARRAY = ^_BOOL_ARRAY;

  LP_BYTE = ^BYTE;
  _BYTE_ARRAY = array[0..65535] of BYTE;
  LP_BYTE_ARRAY = ^_BYTE_ARRAY;

  HANDLE = THandle;
  LP_HANDLE = ^HANDLE;
  _HANDLE_ARRAY = array[0..65535] of HANDLE;
  LP_HANDLE_ARRAY = ^_HANDLE_ARRAY;

  LP_SIZE = ^SIZE;
  _SIZE_ARRAY = array[0..65535] of SIZE;
  LP_SIZE_ARRAY = ^_SIZE_ARRAY;

  LP_SIZE_T = ^SIZE_T;
  _SIZE_T_ARRAY = array[0..65535] of SIZE_T;
  LP_SIZE_T_ARRAY = ^_SIZE_T_ARRAY;

  LP_LPSTR = ^LPSTR;
  LP_LPCTSTR = ^LPCTSTR;
  LP_LPWSTR = ^LPWSTR;

  LP_GUID = ^TGUID;

  LP_UINT = ^UINT;
  _UINT_ARRAY = array[0..65535] of UINT;
  LP_UINT_ARRAY = ^_UINT_ARRAY;

  INT = INTEGER;
  LP_INT = ^INT;
  _INT_ARRAY = array[0..65535] of INT;
  LP_INT_ARRAY = ^_INT_ARRAY;

  LP_UINT8 = ^UINT8;
  _UINT8_ARRAY = array[0..65535] of UINT8;
  LP_UINT8_ARRAY = ^_UINT8_ARRAY;

  LP_UINT16 = ^UINT16;
  _UINT16_ARRAY = array[0..65535] of UINT16;
  LP_UINT16_ARRAY = ^_UINT16_ARRAY;

  LP_UINT32 = ^UINT32;
  _UINT32_ARRAY = array[0..65535] of UINT32;
  LP_UINT32_ARRAY = ^_UINT32_ARRAY;

  LP_UINT64 = ^UINT64;
  _UINT64_ARRAY = array[0..65535] of UINT64;
  LP_UINT64_ARRAY = ^_UINT64_ARRAY;

  LP_INT8 = ^INT8;
  _INT8_ARRAY = array[0..65535] of INT8;
  LP_INT8_ARRAY = ^_INT8_ARRAY;

  LP_INT16 = ^INT16;
  _INT16_ARRAY = array[0..65535] of INT16;
  LP_INT16_ARRAY = ^_INT16_ARRAY;

  LP_INT32 = ^INT32;
  _INT32_ARRAY = array[0..65535] of INT32;
  LP_INT32_ARRAY = ^_INT32_ARRAY;

  LP_INT64 = ^INT64;
  _INT64_ARRAY = array[0..65535] of INT64;
  LP_INT64_ARRAY = ^_INT64_ARRAY;

  POINT = TPoint;
  LP_POINT = ^POINT;
  _POINT_ARRAY = array[0..65535] of POINT;
  LP_POINT_ARRAY = ^_POINT_ARRAY;

  RECT = TRect;
  LP_RECT = ^RECT;
  _RECT_ARRAY = array[0..65535] of RECT;
  LP_RECT_ARRAY = ^_RECT_ARRAY;

  LP_SECURITY_ATTRIBUTES = ^SECURITY_ATTRIBUTES;
  _SECURITY_ATTRIBUTES_ARRAY = array[0..65535] of SECURITY_ATTRIBUTES;
  LP_SECURITY_ATTRIBUTES_ARRAY = ^_SECURITY_ATTRIBUTES_ARRAY;

  D3DCOLORVALUE = record
    r: FLOAT;
    g: FLOAT;
    b: FLOAT;
    a: FLOAT;
  end;
  LP_D3DCOLORVALUE = ^D3DCOLORVALUE;
  _D3DCOLORVALUE_ARRAY = array[0..65535] of D3DCOLORVALUE;
  LP_D3DCOLORVALUE_ARRAY = ^_D3DCOLORVALUE_ARRAY;

IMPLEMENTATION

END.
