pasdoc.exe --graphviz-uses --graphviz-classes --output ZEngineFullDoc --auto-abstract --staronly --write-uses-list --source ZEngineSourcesFullList.txt --include ..\cad_source;..\cad_source\autogenerated;..\cad_source\components\zebase;..\cad_source\other;..\cad_source\zengine\u\undostack
python.exe dottoxml.py ZEngineFullDoc\GVClasses.dot ZEngineFullClasses.graphml
python.exe dottoxml.py ZEngineFullDoc\GVUses.dot ZEngineFullUses.graphml

pause