pasdoc.exe --output selected --auto-abstract --staronly write-uses-list --source selectedFile_source.txt --include ..\cad_source;..\cad_source\autogenerated;..\cad_source\components\zebase;..\cad_source\other;..\cad_source\zengine\u\undostack

pause