md ZCADFullDoc
pasdoc.exe --graphviz-uses --graphviz-classes --output ZCADFullDoc --auto-abstract --staronly --write-uses-list --source ZCADSourcesFullList.txt --include ..\cad_source;..\cad_source\zengine;..\cad_source\autogenerated;..\cad_source\components\zebase;..\cad_source\other;..\cad_source\zengine\u\undostack
dottoxml.py ZCADFullDoc\GVClasses.dot ZCADFullClasses.graphml
dottoxml.py ZCADFullDoc\GVUses.dot ZCADFullUses.graphml

pause