pasdoc.exe --output FullDoc --auto-abstract --staronly --write-uses-list --source SourcesFullList.txt --include ..\cad_source;..\cad_source\autogenerated;..\cad_source\components\zebase;..\cad_source\other;..\cad_source\zengine\u\undostack

pause