md FinishedDoc
pasdoc.exe --output FinishedDoc --auto-abstract --staronly write-uses-list --source SourcesFinishedList.txt --include ..\cad_source;..\cad_source\zengine;..\cad_source\autogenerated;..\cad_source\components\zebase;..\cad_source\other;..\cad_source\zengine\u\undostack

pause