{$DEFINE TCommand  := TGDBPolyDataChangeCommand}
{$DEFINE PTCommand := PTGDBPolyDataChangeCommand}
{$DEFINE TData     := TPolyData}
  {$I TGObjectChangeCommand2IMPL.inc}
{$DEFINE TCommand  := TGDBLayerArrayChangeCommand}
{$DEFINE PTCommand := PTGDBLayerArrayChangeCommand}
{$DEFINE TData     := PGDBLayerProp}
  {$I TGObjectChangeCommand2IMPL.inc}
{$DEFINE TCommand  := TGDBTextStyleArrayChangeCommand}
{$DEFINE PTCommand := PTGDBTextStyleChangeCommand}
{$DEFINE TData     := PGDBTextStyle}
  {$I TGObjectChangeCommand2IMPL.inc}
