{$DEFINE TCommand  := TGDBVertexChangeCommand}
{$DEFINE PTCommand := PTGDBVertexChangeCommand}
{$DEFINE TData     := GDBVertex}
  {$I TGChangeCommandIMPL.inc}

{$DEFINE TCommand  := TGDBDoubleChangeCommand}
{$DEFINE PTCommand := PTGDBDoubleChangeCommand}
{$DEFINE TData     := GDBDouble}
  {$I TGChangeCommandIMPL.inc}

{$DEFINE TCommand  := TGDBCameraBasePropChangeCommand}
{$DEFINE PTCommand := PTGDBCameraBasePropChangeCommand}
{$DEFINE TData     := GDBCameraBaseProp}
  {$I TGChangeCommandIMPL.inc}

{$DEFINE TCommand  := TGDBStringChangeCommand}
{$DEFINE PTCommand := PTGDBStringChangeCommand}
{$DEFINE TData     := GDBString}
  {$I TGChangeCommandIMPL.inc}

{$DEFINE TCommand  := TGDBPoinerChangeCommand}
{$DEFINE PTCommand := PTGDBPoinerChangeCommand}
{$DEFINE TData     := GDBPointer}
  {$I TGChangeCommandIMPL.inc}

{$DEFINE TCommand  := TGDBBooleanChangeCommand}
{$DEFINE PTCommand := PTGDBBooleanChangeCommand}
{$DEFINE TData     := GDBBoolean}
  {$I TGChangeCommandIMPL.inc}

{$DEFINE TCommand  := TGDBGDBByteChangeCommand}
{$DEFINE PTCommand := PTGDBGDBByteChangeCommand}
{$DEFINE TData     := GDBByte}
  {$I TGChangeCommandIMPL.inc}

